spring:
  datasource:
    url: jdbc:mysql://localhost:3307/recipe_app_prod
    username: ${DB_PROD_USERNAME}
    password: ${DB_PROD_PASSWORD}
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false